# Generated by Django 3.1 on 2021-08-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('eMail', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('photoUrl', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceDetails',
            fields=[
                ('residenceId', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('residenceName', models.CharField(max_length=50)),
                ('residenceType', models.CharField(max_length=10)),
                ('bedRooms', models.CharField(max_length=1)),
                ('washRooms', models.CharField(max_length=1)),
                ('carpetArea', models.CharField(max_length=10)),
                ('parking', models.BooleanField(default=False)),
                ('locationLA', models.CharField(max_length=20)),
                ('locationLO', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owner')),
            ],
        ),
    ]
