# Generated by Django 3.1 on 2021-08-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_residenceimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResidenceImages',
        ),
    ]
