# Generated by Django 3.1 on 2021-08-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_residenceimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='residenceImages/', verbose_name='image')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.residencedetails')),
            ],
        ),
    ]
