# Generated by Django 3.1 on 2021-08-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_residenceimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residenceimages',
            name='residence',
        ),
        migrations.DeleteModel(
            name='ResidenceDetails',
        ),
        migrations.DeleteModel(
            name='ResidenceImages',
        ),
    ]
