# Generated by Django 3.1 on 2021-08-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210826_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceDetails',
            fields=[
                ('residenceId', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('residenceName', models.CharField(max_length=50)),
                ('residenceType', models.CharField(max_length=10)),
                ('bedRooms', models.CharField(max_length=1)),
                ('washRooms', models.CharField(max_length=1)),
                ('carpetArea', models.CharField(max_length=10)),
                ('parking', models.BooleanField(default=False)),
                ('cost', models.CharField(max_length=6)),
                ('locationLA', models.CharField(max_length=20)),
                ('locationLO', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owner')),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='residenceImages/', verbose_name='image')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.residencedetails')),
            ],
        ),
    ]
