# Generated by Django 3.1 on 2021-09-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_qanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanda',
            name='answer',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
